apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nameClient }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hostClient }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nameClient }}
                port:
                  number: 80
  tls:
  - hosts:
      - {{ .Values.hostClient }}
    secretName: ofa-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nameServer }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hostServer }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nameServer }}
                port:
                  number: 80
